// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnxeozpmchjruixhxbux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZueGVvenBtY2hqcnVpeGh4YnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTkwNTUsImV4cCI6MjA2NzczNTA1NX0.SaftTVQYT-oOKIdFn2Go0OHrRIQYouIdiXdZoEoE73k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});